name: MS Teams Notification

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
       with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Whew! Everything is right with the world again! 
        notification-color: 28a745 
        timezone: America/Denver 
