name: MS Teams Notification

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Send a Notification
        uses: thechetantalwar/teams-notify@v2
        with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Please approve the merge request."
